# -*- coding: utf-8 -*-
"""train_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oARYWp2K2UZVk6mVxiLvTmfv0JYrgvVO
"""

!pip install numpy scikit-learn

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

import pickle
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

data_dict = pickle.load(open('/content/drive/MyDrive/data.pickle', 'rb'))

EXPECTED_FEATURES = 42

valid_data = []
valid_labels = []

for i in range(len(data_dict['data'])):
    if len(data_dict['data'][i]) == EXPECTED_FEATURES:
        valid_data.append(data_dict['data'][i])
        valid_labels.append(data_dict['labels'][i])
    else:
        print(f"Skipping sample {i}: Invalid feature length = {len(data_dict['data'][i])}")

data = np.asarray(valid_data)
labels = np.asarray(valid_labels)

x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, shuffle=True)

model = RandomForestClassifier()
model.fit(x_train, y_train)

y_predict = model.predict(x_test)
score = accuracy_score(y_predict, y_test)
print('{}% of samples were classified correctly!'.format(score * 100))

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_predict)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)

plt.figure(figsize=(8, 6))
disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.show()

train_sizes = [0.1, 0.3, 0.5, 0.7, 0.9]
accuracies = []

for size in train_sizes:
    x_train_tmp, _, y_train_tmp, _ = train_test_split(
        data, labels, train_size=size, shuffle=True
    )
    model_tmp = RandomForestClassifier()
    model_tmp.fit(x_train_tmp, y_train_tmp)
    y_pred_tmp = model_tmp.predict(x_test)
    acc = accuracy_score(y_test, y_pred_tmp)
    accuracies.append(acc)

# Plotting
plt.plot(train_sizes, [a * 100 for a in accuracies], marker='o')
plt.title("Accuracy vs Training Set Size")
plt.xlabel("Training Set Size")
plt.ylabel("Accuracy (%)")
plt.grid(True)
plt.show()

with open('model.p', 'wb') as f:
    pickle.dump({'model': model}, f)

from google.colab import files
files.download('model.p')